### ISSUE TITLE
Pikatehtävien 5.2.3 ja 5.2.4 kysymysteksti on kadonnut

### ISSUE THREAD

**Issue by epicharri** [rage/tietokoneen-toiminnan-jatkokurssi-material#48]
Pikatehtävien 5.2.3 ja 5.2.4 kysymysteksti on kadonnut. Vain kysymyksen otsikko ja vastausvaihtoehdot ovat näkyvillä. Saisiko kysymystekstit palautettua?

**Comment by eoikarin** [comment]
Korjattu.
